name: Update Plugin List

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python_verion: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tabulate
      - name: Update Plugin List
        run: python scripts/plugin_list.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update plugin list
          branch: update-plugin-list/patch
          delete-branch: true
          branch-suffix: short-commit-hash
          title: '[Workflow] Update plugin list'
          body: Update plugin list
