name: Update Plugin List

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install packaging requests tabulate[widechars]
      - name: Update Plugin List
        run: python scripts/plugin_list.py
      - name: GitHub Script
        uses: actions/github-script@v3.0.0
        with:
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '[automated] Update plugin list',
              head: '[automated] Update plugin list',
              base: 'master',
            });
